from enum import Enum

class FSMState(str, Enum):
    ISSUE_RECEIVED = "ISSUE_RECEIVED"
    ANALYZING = "ANALYZING"
    SPEC_READY = "SPEC_READY"
    LOCALIZATION = "LOCALIZATION"
    LOCALIZING = "LOCALIZING"
    PLANNING = "PLANNING"
    REPAIR = "REPAIR"
    IMPLEMENTING = "IMPLEMENTING"
    VALIDATING = "VALIDATING"
    DEBUGGING = "DEBUGGING"
    VERIFICATION = "VERIFICATION"
    VERIFYING = "VERIFYING"
    SECURITY_CHECK = "SECURITY_CHECK"
    MUTATION_TESTING = "MUTATION_TESTING"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    PR_READY = "PR_READY"
    MERGE = "MERGE"
    COMPLETED = "COMPLETED"
    TERMINAL_SUCCESS = "TERMINAL_SUCCESS"
    TERMINAL_FAILED = "TERMINAL_FAILED"

    # Compatibility alias
    INIT = "INIT"

class AutonomyTier(str, Enum):
    LOW = "LOW_AUTONOMOUS_MERGE"
    MEDIUM = "MEDIUM_HUMAN_CONSENT"
    HIGH = "HIGH_MANDATORY_REVIEW"
